[package]
name = "sqlite_nostd"
version = "0.1.0"
edition = "2021"

[lib]
name = "sqlite_nostd"
crate-type = ["rlib"]

[dependencies]
sqlite3_capi = { path="../sqlite3_capi"}
sqlite3_allocator = { path="../sqlite3_allocator" }
num-traits = { version = "0.2.15", default-features = false }
num-derive = "0.3"

[features]
loadable_extension = ["sqlite3_capi/loadable_extension"]
static = ["sqlite3_capi/static"]
omit_load_extension = ["sqlite3_capi/omit_load_extension"]
