#!/usr/bin/env python3

import os
import sys
import subprocess
import time


def start_server_cmd():
    basedir = os.path.dirname(os.path.realpath(__file__))
    binary = os.path.realpath(os.path.join(basedir, "../target/debug/server"))
    return [binary, "serve"]


cmd = start_server_cmd()

retcode = 0
print("Starting server...", end="")
sys.stdout.flush()
process = subprocess.Popen(cmd)
try:
    time.sleep(1)
    ret = process.poll()
    if ret:
        print(" FAIL.\n")
        exit(1)
    time.sleep(5)
    print(" done.\n")
    if os.system("make -C testing/") != 0:
        retcode = 1
        raise Exception("Tests failed")
finally:
    process.kill()
exit(retcode)
