# This makefile exists primarily to simplify/speed up development from
# emacs. It is not part of the canonical build process.
default:
	make -C ../.. fiddle -e emcc_opt=-O0

clean:
	make -C ../../ clean-fiddle
