ignore:
  - "libsqlite3-sys/bindgen-bindings"
  - "libsqlite3-sys/sqlite3"
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
