# Estimated relative cost of various jobs, based on the "estkey" field.
# Computed by the "test/testrunner.tcl estwork" command.
#
set estwork((fuzzcheck)) 1291
set estwork((fuzzcheck-asan)) 2427
set estwork((fuzzcheck-ubsan)) 2749
set estwork((sessionfuzz)) 1276
set estwork((sqlite3)) 1281
set estwork((testfixture)) 1546
set estwork(aggerror.test) 5
set estwork(alter.test) 20
set estwork(alter3.test) 2
set estwork(alterauth.test) 5
set estwork(altercol.test) 5
set estwork(alterdropcol.test) 17
set estwork(alterlegacy.test) 2
set estwork(altertab.test) 34
set estwork(altertab2.test) 2
set estwork(altertab3.test) 12
set estwork(amatch1.test) 40
set estwork(atof1.test) 146
set estwork(atomic2.test) 2
set estwork(auth.test) 2
set estwork(autoindex1.test) 5
set estwork(autoindex3.test) 5
set estwork(autovacuum.test) 15
set estwork(avfs.test) 16
set estwork(avtrans.test) 285
set estwork(backup2.test) 15
set estwork(bestindex4.test) 12
set estwork(bigrow.test) 5
set estwork(bitvec.test) 94
set estwork(bld) 99
set estwork(blob.test) 2
set estwork(boundary1.test) 8
set estwork(boundary2.test) 16
set estwork(boundary3.test) 14
set estwork(btree01.test) 20
set estwork(busy.test) 2
set estwork(busy2.test) 288
set estwork(capi3.test) 5
set estwork(capi3b.test) 6
set estwork(capi3c.test) 5
set estwork(capi3d.test) 8
set estwork(capi3e.test) 20
set estwork(changes.test) 11
set estwork(chunksize.test) 5
set estwork(closure01.test) 63
set estwork(collate5.test) 2
set estwork(conflict.test) 8
set estwork(conflict2.test) 4
set estwork(conflict3.test) 8
set estwork(corrupt2.test) 2
set estwork(corrupt4.test) 91
set estwork(corrupt7.test) 5
set estwork(corrupt8.test) 3
set estwork(corruptB.test) 4
set estwork(corruptF.test) 6
set estwork(count.test) 18
set estwork(crash8.test) 14
set estwork(createtab.test) 3
set estwork(csv01.test) 7
set estwork(cursorhint.test) 4
set estwork(date.test) 17
set estwork(date4.test) 64
set estwork(date5.test) 3
set estwork(dbdata.test) 77
set estwork(dbfuzz001.test) 2
set estwork(dbstatus.test) 4
set estwork(decimal.test) 2
set estwork(delete.test) 4
set estwork(diskfull.test) 34
set estwork(e_blobbytes.test) 11
set estwork(e_createtable.test) 14
set estwork(e_delete.test) 3
set estwork(e_droptrigger.test) 6
set estwork(e_dropview.test) 2
set estwork(e_expr.test) 251
set estwork(e_select.test) 5
set estwork(e_select2.test) 5
set estwork(e_vacuum.test) 6
set estwork(e_walauto.test) 51
set estwork(e_walckpt.test) 6
set estwork(enc.test) 2
set estwork(enc3.test) 11
set estwork(enc4.test) 3
set estwork(eval.test) 2
set estwork(exists.test) 4
set estwork(existsexpr.test) 44
set estwork(expert1.test) 14
set estwork(expr.test) 5
set estwork(filectrl.test) 5
set estwork(filefmt.test) 6
set estwork(fkey2.test) 9
set estwork(fpconv1.test) 40
set estwork(fts3aa.test) 18
set estwork(fts3ad.test) 10
set estwork(fts3ag.test) 6
set estwork(fts3aj.test) 8
set estwork(fts3am.test) 5
set estwork(fts3auto.test) 29
set estwork(fts3b.test) 41
set estwork(fts3c.test) 22
set estwork(fts3conf.test) 3
set estwork(fts3corrupt4.test) 7
set estwork(fts3corrupt5.test) 8
set estwork(fts3corrupt6.test) 13
set estwork(fts3d.test) 2
set estwork(fts3defer2.test) 2
set estwork(fts3expr.test) 10
set estwork(fts3expr2.test) 8
set estwork(fts3expr3.test) 145
set estwork(fts3f.test) 9
set estwork(fts3first.test) 3
set estwork(fts3matchinfo.test) 4
set estwork(fts3misc.test) 54
set estwork(fts3prefix.test) 4
set estwork(fts3prefix2.test) 8
set estwork(fts3query.test) 23
set estwork(fts3varint.test) 2
set estwork(fts4aa.test) 34
set estwork(fts4content.test) 5
set estwork(fts4incr.test) 19
set estwork(fts4noti.test) 3
set estwork(fts4opt.test) 129
set estwork(fts4unicode.test) 45
set estwork(fts5aa.test) 442
set estwork(fts5ab.test) 54
set estwork(fts5ad.test) 33
set estwork(fts5ae.test) 3
set estwork(fts5af.test) 13
set estwork(fts5ag.test) 13
set estwork(fts5ah.test) 265
set estwork(fts5al.test) 2
set estwork(fts5auto.test) 92
set estwork(fts5connect.test) 5
set estwork(fts5content.test) 9
set estwork(fts5contentless.test) 23
set estwork(fts5contentless2.test) 189
set estwork(fts5contentless4.test) 234
set estwork(fts5contentless5.test) 9
set estwork(fts5delete.test) 62
set estwork(fts5doclist.test) 11
set estwork(fts5expr.test) 10
set estwork(fts5full.test) 42
set estwork(fts5hash.test) 17
set estwork(fts5integrity.test) 84
set estwork(fts5interrupt.test) 16
set estwork(fts5locale.test) 5
set estwork(fts5matchinfo.test) 11
set estwork(fts5merge.test) 29
set estwork(fts5merge2.test) 9
set estwork(fts5misc.test) 8
set estwork(fts5multiclient.test) 2
set estwork(fts5optimize.test) 13
set estwork(fts5optimize2.test) 737
set estwork(fts5optimize3.test) 280
set estwork(fts5origintext.test) 144
set estwork(fts5origintext3.test) 8
set estwork(fts5origintext4.test) 30
set estwork(fts5origintext5.test) 462
set estwork(fts5origintext6.test) 55
set estwork(fts5porter.test) 57
set estwork(fts5query.test) 8
set estwork(fts5restart.test) 10
set estwork(fts5rowid.test) 35
set estwork(fts5secure.test) 61
set estwork(fts5secure3.test) 796
set estwork(fts5secure4.test) 141
set estwork(fts5secure5.test) 29
set estwork(fts5secure6.test) 33
set estwork(fts5secure7.test) 680
set estwork(fts5simple.test) 7
set estwork(fts5simple2.test) 2
set estwork(fts5synonym.test) 13
set estwork(fts5synonym2.test) 384
set estwork(fts5tok2.test) 92
set estwork(fts5tokenizer.test) 2
set estwork(fts5tokenizer3.test) 8
set estwork(fts5trigram.test) 2
set estwork(fts5unicode2.test) 28
set estwork(fts5unicode3.test) 72
set estwork(fts5unindexed.test) 7
set estwork(fts5update.test) 161
set estwork(fts5update2.test) 11
set estwork(fts5vocab.test) 11
set estwork(fts5vocab2.test) 15
set estwork(func.test) 36
set estwork(fuzz) 68
set estwork(fuzz-oss1.test) 11
set {estwork(fuzzcheck --slice)} 499
set {estwork(fuzzcheck fuzzdata1.db)} 301
set {estwork(fuzzcheck fuzzdata2.db)} 275
set {estwork(fuzzcheck fuzzdata3.db)} 72
set {estwork(fuzzcheck fuzzdata4.db)} 30
set {estwork(fuzzcheck fuzzdata5.db)} 299
set {estwork(fuzzcheck fuzzdata6.db)} 91
set {estwork(fuzzcheck fuzzdata7.db)} 201
set {estwork(fuzzcheck fuzzdata8.db)} 331
set {estwork(fuzzcheck-asan --slice)} 2037
set {estwork(fuzzcheck-asan fuzzdata1.db)} 3112
set {estwork(fuzzcheck-asan fuzzdata2.db)} 8753
set {estwork(fuzzcheck-asan fuzzdata3.db)} 459
set {estwork(fuzzcheck-asan fuzzdata4.db)} 123
set {estwork(fuzzcheck-asan fuzzdata5.db)} 1178
set {estwork(fuzzcheck-asan fuzzdata6.db)} 1356
set {estwork(fuzzcheck-asan fuzzdata7.db)} 938
set {estwork(fuzzcheck-asan fuzzdata8.db)} 1451
set {estwork(fuzzcheck-ubsan --slice)} 1729
set {estwork(fuzzcheck-ubsan fuzzdata1.db)} 1180
set {estwork(fuzzcheck-ubsan fuzzdata2.db)} 876
set {estwork(fuzzcheck-ubsan fuzzdata3.db)} 306
set {estwork(fuzzcheck-ubsan fuzzdata4.db)} 95
set {estwork(fuzzcheck-ubsan fuzzdata5.db)} 1356
set {estwork(fuzzcheck-ubsan fuzzdata6.db)} 333
set {estwork(fuzzcheck-ubsan fuzzdata7.db)} 883
set {estwork(fuzzcheck-ubsan fuzzdata8.db)} 1124
set estwork(fuzzer1.test) 6
set estwork(gencol1.test) 3
set estwork(hook.test) 2
set estwork(in4.test) 4
set estwork(in7.test) 6
set estwork(incrblob2.test) 2
set estwork(incrblob3.test) 5
set estwork(incrvacuum.test) 10
set estwork(incrvacuum2.test) 17
set estwork(incrvacuum3.test) 17
set estwork(index.test) 3
set estwork(index2.test) 8
set estwork(index4.test) 33
set estwork(index5.test) 99
set estwork(index6.test) 2
set estwork(indexexpr1.test) 2
set estwork(insert3.test) 5
set estwork(insert4.test) 2
set estwork(intarray.test) 8
set estwork(intck1.test) 34
set estwork(intck2.test) 37
set estwork(interrupt.test) 28
set estwork(io.test) 3
set estwork(join.test) 3
set estwork(join3.test) 6
set estwork(join5.test) 20
set estwork(join7.test) 2
set estwork(join8.test) 3
set estwork(join9.test) 2
set estwork(joinA.test) 11
set estwork(joinB.test) 7
set estwork(joinC.test) 6
set estwork(joinD.test) 168
set estwork(json103.test) 6
set estwork(json106.test) 690
set estwork(keyword1.test) 3
set estwork(like2.test) 2
set estwork(like3.test) 2
set estwork(limit.test) 3
set estwork(literal.test) 6
set estwork(lock.test) 39
set estwork(lock4.test) 2
set estwork(lock5.test) 4
set estwork(make) 102
set estwork(manydb.test) 12
set estwork(mem5.test) 2
set estwork(memdb.test) 9
set estwork(memdb1.test) 2
set estwork(memjournal2.test) 164
set estwork(memsubsys1.test) 8
set estwork(misc1.test) 6
set estwork(misc2.test) 6
set estwork(misc5.test) 11
set estwork(misc8.test) 5
set estwork(mmap1.test) 8
set estwork(mmap2.test) 10
set estwork(mmapwarm.test) 2
set estwork(multiplex.test) 30
set estwork(multiplex2.test) 7
set estwork(nan.test) 2
set estwork(notify3.test) 5
set estwork(orderby1.test) 11
set estwork(orderby2.test) 2
set estwork(orderby5.test) 11
set estwork(orderby6.test) 6
set estwork(orderby8.test) 20
set estwork(orderbyA.test) 2
set estwork(oserror.test) 7
set estwork(ovfl.test) 11
set estwork(pager1.test) 81
set estwork(pager2.test) 129
set estwork(pagesize.test) 3
set estwork(percentile.test) 86
set estwork(pragma.test) 4
set estwork(pragma4.test) 18
set estwork(printf.test) 21
set estwork(printf2.test) 5
set estwork(quota.test) 14
set estwork(randexpr1.test) 35
set estwork(rbu10.test) 16
set estwork(rbu13.test) 5
set estwork(rbuexlock.test) 5
set estwork(rbumisc.test) 2
set estwork(rbutemplimit.test) 2
set estwork(readonly.test) 95
set estwork(recover.test) 3
set estwork(recover1.test) 7
set estwork(recovercorrupt3.test) 5
set estwork(recoverold.test) 7
set estwork(recoverpgsz.test) 6
set estwork(recoverrowid.test) 3
set estwork(returning1.test) 6
set estwork(rollback2.test) 2
set estwork(round1.test) 261
set estwork(rowhash.test) 85
set estwork(rowid.test) 3
set estwork(rowvalue.test) 2
set estwork(rowvalue2.test) 38
set estwork(rowvalue4.test) 2
set estwork(rowvalueA.test) 2
set estwork(rowvaluevtab.test) 2
set estwork(rtree1.test) 4
set estwork(rtree2.test) 758
set estwork(rtree6.test) 6
set estwork(rtree8.test) 15
set estwork(rtree9.test) 15
set estwork(rtreeA.test) 7
set estwork(rtreeB.test) 7
set estwork(rtreeE.test) 47
set estwork(rtreeH.test) 24
set estwork(rtreecheck.test) 2
set estwork(rtreedoc.test) 8
set estwork(rtreedoc3.test) 76
set estwork(savepoint.test) 10
set estwork(savepoint2.test) 57
set estwork(schema2.test) 15
set estwork(schema3.test) 2
set estwork(schema5.test) 5
set estwork(select1.test) 2
set estwork(select2.test) 17
set estwork(select3.test) 2
set estwork(selectA.test) 2
set estwork(selectB.test) 2
set estwork(selectG.test) 30
set estwork(session1.test) 5
set estwork(session2.test) 33
set estwork(session5.test) 63
set estwork(session9.test) 3
set estwork(sessionG.test) 60
set estwork(sessionH.test) 18
set estwork(sessionalter.test) 3
set estwork(sessionat.test) 2
set estwork(sessionblob.test) 3
set {estwork(sessionfuzz sessionfuzz-data1.db)} 5
set estwork(sessioninvert.test) 2
set estwork(sessionnoop.test) 2
set estwork(sessionnoop2.test) 8
set estwork(sessionrebase.test) 8
set estwork(shared.test) 7
set estwork(sharedA.test) 48
set estwork(shell1.test) 36
set estwork(shell2.test) 11
set estwork(shell3.test) 3
set estwork(shell4.test) 2
set estwork(shell5.test) 16
set estwork(shell6.test) 3
set estwork(shell8.test) 104
set estwork(shell9.test) 3
set estwork(shellA.test) 2
set estwork(shmlock.test) 27
set estwork(sidedelete.test) 10
set estwork(skipscan1.test) 7
set estwork(skipscan2.test) 5
set estwork(sort.test) 38
set estwork(sort2.test) 540
set estwork(sort5.test) 16
set estwork(spellfix.test) 5
set estwork(spellfix2.test) 5
set estwork(spellfix4.test) 11
set estwork(starschema1.test) 2
set estwork(strict1.test) 5
set estwork(swarmvtab.test) 110
set estwork(swarmvtab3.test) 14
set estwork(syscall.test) 4
set estwork(table.test) 62
set estwork(tableapi.test) 8
set estwork(tcl) 1
set estwork(tclsqlite.test) 29
set estwork(temptable2.test) 274
set estwork(thread3.test) 21
set estwork(timediff1.test) 5
set estwork(tkt-2d1a5c67d.test) 6
set estwork(tkt-38cb5df375.test) 2
set estwork(tkt-4dd95f6943.test) 2
set estwork(tkt-5e10420e8d.test) 5
set estwork(tkt-6bfb98dfc0.test) 5
set estwork(tkt-80e031a00f.test) 25
set estwork(tkt-9d68c883.test) 3
set estwork(tkt-9f2eb3abac.test) 5
set estwork(tkt-b1d3a2e531.test) 5
set estwork(tkt-b72787b1.test) 5
set estwork(tkt-b75a9ca6b0.test) 8
set estwork(tkt-d11f09d36e.test) 9
set estwork(tkt-fc62af4523.test) 10
set estwork(tkt1435.test) 7
set estwork(tkt1644.test) 5
set estwork(tkt1667.test) 20
set estwork(tkt1873.test) 2
set estwork(tkt2192.test) 3
set estwork(tkt2285.test) 19
set estwork(tkt2332.test) 2
set estwork(tkt2409.test) 24
set estwork(tkt3334.test) 5
set estwork(tkt3357.test) 10
set estwork(tkt3630.test) 2
set estwork(tkt3832.test) 8
set estwork(tkt3838.test) 5
set estwork(tkt3918.test) 3
set estwork(tkt4018.test) 48
set estwork(tokenize.test) 9
set estwork(tpch01.test) 6
set estwork(trans.test) 258
set estwork(trigger2.test) 15
set estwork(trigger5.test) 2
set estwork(trigger8.test) 30
set estwork(triggerA.test) 36
set estwork(triggerB.test) 4
set estwork(triggerC.test) 67
set estwork(triggerD.test) 3
set estwork(types.test) 2
set estwork(types2.test) 2
set estwork(unionall2.test) 9
set estwork(unionvtab.test) 2
set estwork(update.test) 7
set estwork(upsert3.test) 6
set estwork(upsert5.test) 5
set estwork(vacuum.test) 2
set estwork(vacuum5.test) 3
set estwork(vacuum6.test) 174
set estwork(vacuummem.test) 132
set estwork(varint.test) 8
set estwork(view.test) 2
set estwork(vtab1.test) 13
set estwork(vtab6.test) 12
set estwork(vtabC.test) 33
set estwork(vtabD.test) 56
set estwork(vtab_alter.test) 6
set estwork(wal.test) 38
set estwork(wal2.test) 7
set estwork(wal3.test) 196
set estwork(wal4.test) 70
set estwork(wal5.test) 22
set estwork(wal64k.test) 20
set estwork(wal7.test) 3
set estwork(wal9.test) 24
set estwork(walbak.test) 2
set estwork(walcksum.test) 3
set estwork(walcrash4.test) 59
set estwork(waloverwrite.test) 3
set estwork(walpersist.test) 6
set estwork(walprotocol2.test) 2
set estwork(walro2.test) 11
set estwork(walsetlk.test) 1610
set estwork(walsetlk3.test) 3
set estwork(walsetlk_recover.test) 193
set estwork(walshared.test) 5
set estwork(walvfs.test) 476
set estwork(where.test) 24
set estwork(where3.test) 4
set estwork(where6.test) 2
set estwork(where7.test) 20
set estwork(where8.test) 95
set estwork(where9.test) 16
set estwork(whereB.test) 5
set estwork(whereE.test) 6
set estwork(whereN.test) 2
set estwork(window1.test) 5
set estwork(window2.test) 8
set estwork(window3.test) 89
set estwork(window4.test) 3
set estwork(window5.test) 2
set estwork(window8.test) 33
set estwork(windowA.test) 5
set estwork(windowD.test) 6
set estwork(with1.test) 114
set estwork(with2.test) 4
set estwork(with5.test) 2
set estwork(withM.test) 4
set estwork(without_rowid1.test) 2
set estwork(without_rowid3.test) 9
set estwork(without_rowid4.test) 6
