# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.cpus = 4
    v.memory = 8192
  end

  config.vm.box = "debian/buster64"
  config.vm.network "forwarded_port", guest: 8080, host: 8081

  config.vm.synced_folder "../cluster-test", "/jepsen", type: "rsync"

  config.vm.provision "shell" do |shell|
    shell.inline  = <<-SCRIPT
      ssh-keygen -t rsa -q -f "/home/vagrant/.ssh/id_rsa" -N ""
    SCRIPT
  end
  # setup lxc nodes
  config.vm.provision "shell" do |shell|
    shell.privileged = true
    shell.path = "provision.sh"
    shell.reboot = true
  end

  # always start nodes on startup
  config.vm.provision "shell", run: "always" do |shell|
    shell.privileged = true
    shell.inline = <<-SCRIPT
        for i in {1..10}; do
          lxc-start -d -n n$i
        done
      SCRIPT
    end
end
