name: Go bindings tests CI

on:
  push:
    branches: [ "main" ]
  pull_request:
  merge_group:
    branches: [ "main" ]

jobs:
  golang-bindings:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # needed because we run out of disk space during tests
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # when set to "true" but frees about 6 GB
        tool-cache: true

    - uses: dtolnay/rust-toolchain@stable
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.21'
    - name: get TCL
      run: sudo apt-get install -y tcl8.6-dev

    - name: Install Protoc
      uses: arduino/setup-protoc@v2

    - name: Set up cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-

    - name: Build crates
      run: cargo build --release

    - name: Run Go bindings tests
      working-directory: bindings/go
      run: LD_LIBRARY_PATH=../../target/release go test
